development:
  adapter: mysql2  
  encoding: utf8
  database: animal-rescue-hub-development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2  
  encoding: utf8
  database: animal-rescue-hub-test
  pool: 5
  username: root
  password:
    
# production:
#   adapter: mysql2  
#   encoding: utf8
#   database: heroku_3592d707c65e01c
#   username: b21a2c364a3080
#   password: 7d1be879
#   host: us-cdbr-east-03.cleardb.com
#   pool: 5