development:
  adapter: mysql2  
  encoding: utf8
  database: animal-rescue-hub-development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2  
  encoding: utf8
  database: animal-rescue-hub-test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2  
  encoding: utf8
  database: heroku_ff3dd25dac4640a
  username: bd3b33b091b4a7
  password: c6935295
  host: us-cdbr-east-03.cleardb.com
  pool: 5
  